exit

show system

show board info

show board <slot-id> info

show board status

show configuration

save configuration

clear configuration

restore configuration default [quiet]

reset system [quiet]

import configuration ftp <ip_address> "<account_name>" "<passwd>" "<file_name>" "[path]"

export configuration ftp <ip_address> "<account_name>" "<passwd>" "<file_name>" "[path]"

set platform <slot-id> s40

set platform <slot-id> s320

sysname "<sysname>"

datetime <slot-id> "[datetime]"

timezone <slot-id> "[timezone]"

reset board <slot-id>

exitshell

ipconfig <ip> <mask>

gateway <ip>

set slot <slot-id> opmode fr_16xe_fb_11qxe_2dxe

set slot <slot-id> opmode fr_20xe_fb_9qxe_4dxe

set slot <slot-id> opmode fr_24xe_fb_8qxe_4dxe

show slot

set chassis id <id>

set chassis mode dual_star

set chassis mode dual_dual_star

set slot <slot-id> ac1200 backplane rxtx mode receive

set slot <slot-id> ac1200 backplane rxtx mode transceiving

slot <slot-id> module <module-id> portmap

set system name <string>

show current application

show available application

add application <url> "[local_path]"

delete application "<filename>"

select application "<filename>" [sequence]

undo select application "<filename>"

om list application

om add application <url>

om delete application "<version>"

om select application "<version>" <slot_min> [slot_max]

om undo select application "<version>" <slot_min> [slot_max]


set interface <interface_list> autoneg on

set interface <interface_list> autoneg off

set interface <interface_list> pause on

set interface <interface_list> pause off

set interface <interface_list> shutdown

set interface <interface_list> no_shutdown

set interface <interface_list> force up enable 

set interface <interface_list> force up disable

set interface <interface_list> duplex full

set interface <interface_list> duplex half

set interface <interface_list> speed <1000|10000>

set interface <interface_list> mac_address learning on

set interface <interface_list> mac_address learning off

show interface <interface_list> info

show interface <interface_list> status

show interface <interface_list> counter [verbose]

clear interface <interface_list> counter

set interface <interface_list> mode loopback

set interface <interface_list> mode normal

set interface <interface_list> connect to fpga {ab, a9}

set interface <interface_list> disconnect from fpga

set interface <interface_list> connect to ac1200

set interface <interface_list> disconnect to ac1200

set interface <interface_list> descript <string>

add inports <inports_id> <interface_list>

delete inports <inports_id> <interface_list>

add outports <outports_id> hash <interface_list>

add outports <outports_id> hash <interface_list> weight <weight>

add outports <outports_id> mc <interface_list>

delete outports <outports_id> <interface_list>

set outports <outports_id> load_balance {sip, dip, ip, smac, dmac, mac}

set outports global load_balance {sip, dip, ip, smac, dmac, mac}

set load_balance port enable

set load_balance port disable

set slot <slot-id> load_balance port enable

set slot <slot-id> load_balance port disable

show inports <inports_id>

show inports all

show outports <outports_id>

show outports all

set failover enable

set failover disable

set failover interval <interval>

set inports <inports_id> pvlan enable

set inports <inports_id> pvlan disable

set inports <inports_id> pvlan id <id>

set inports <inports_id> pvlan id auto

set inports rx_vlantag replace

set inports rx_vlantag reserve

set slot <slot-id> inports rx_vlantag replace

set slot <slot-id> inports rx_vlantag reserve

set outports <outports_id> vlan untag enable

set outports <outports_id> vlan untag disable


add mac static <mac_addr> inports <inports_id> outports <outports_id> 

delete mac static <mac_addr> inports <inports_id>

delete mac static all 

show mac static

show mac static <mac_addr> [verbose]

show mac static inports <inports_id> [verbose]

show mac static outports <outports_id> [verbose]

show mac dynamic 

show mac dynamic <mac_addr>

show mac dynamic inports <inports_id> 

show mac dynamic outports <outports_id>

delete mac dynamic <mac_addr>

delete mac dynamic all

mac aging_time <aging_time>

show mac aging_time


snmp start

snmp restart

snmp stop

snmp restore configuration

snmp status

snmp show configuration

snmp set sysname "<value>"

snmp set syscontact "<value>"

snmp set syslocation "<value>"

snmp set rocommunity "<value>"

snmp set rwcommunity "<value>"

snmp set trap version "<value>"

snmp set username "<value>"

snmp set auth type md5

snmp set auth type sha

snmp set auth password "<value>"

snmp set priv type des

snmp set priv type aes

snmp set priv password "<value>"

snmp set access noauth

snmp set access auth

snmp set access priv

snmp add trap ip <ip_addr>

snmp delete trap ip <ip_addr>

snmp trap interface fcs threshold <value>
snmp trap interface drop threshold <value>
snmp trap cpu overload threshold <value>
snmp trap memory overload threshold <value>

show snmp trap threshold value

help link_protect

help infoshow

help l2cmds

help interface

help rule

help trunk

help system

help configuration

help snmp

help inports 

help outports 


help set rule

help show rule


help set l2cmds

help show l2cmds

help set interface

help show interface

help clear interface

help add inports

help delete inports

help add outports

help delete outports

help set rule

help show rule

help snmp status

help snmp start

help snmp restart

help snmp stop

help snmp show configuration

help snmp set

help log

help log set

help log show



log enable {info|rule|error|warn|all}

log disable {info|rule|error|warn|all}

log host <host_ip> [port]

log no host <host_ip> [port]

log host local

show log [line]

show log info [line]

show log rule [line]

show log trace [line]

show log error [line]

show log <yyyy-mm-dd>

show log from <yyyy-mm-dd> to <yyyy-mm-dd>

reset log

set <ud_id> mode <ud_mode> offset <ud_offset>

add rule <rule_id> <class_entry>

delete rule <rule_id> entry <entry_id>

delete rule <rule_id> entry all

show rule <rule_id>

set rule <rule_id> inports <inport_id> fw drop

set rule <rule_id> inports <inport_id> fw drop outervlan <min> <max>

set rule <rule_id> inports <inport_id> fw outports <outports_list>

set rule <rule_id> inports <inport_id> fw outports <outports_list> outervlan <min> <max>

soc install

soc uninstall

rule clear

cli_debug acl rule <id>

show rule <rule_id> counter

show rule <rule_id> entry <entry_id> counter

clear rule <rule_id> counter

clear rule <rule_id> entry <entry_id> counter

rcload <slot-id> <config_file>

set interface <smp> mirror to <smp>

set interface <smp> vlan_s <int> vlanmask <int> replace by <int>

set interface <smp> outervlan <int> vlanmask <int> replace by <int>

warm synconfig enable

warm synconfig disable

link_protect create <olp_id>
link_protect create <olp_id> <olp_property>

link_protect destroy <olp_id>

link_protect interface add <olp_id> <smp>

link_protect interface delete <olp_id> <smp>

link_protect interface type set <olp_id> <if_type>

link_protect interface type set <olp_id> <smp> <if_type>

link_protect monitor <id> link on

link_protect monitor <id> link off

link_protect monitor <id> fcs on

link_protect monitor <id> fcs off

link_protect monitor <id> traffic on

link_protect monitor <id> traffic off

link_protect monitor all <type> on

link_protect monitor all <type> off

link_protect status show <olp_id>

link_protect set inline min rx_rate <rate>

link_protect set inline min tx_rx_percent <percent>

link_protect set inline min rx_fcs_rate <rate>

link_protect set inline min tx_fcs_rate <rate>

link_protect set monitor min tx_rate <rate>

link_protect set monitor min rx_tx_percent <percent>

link_protect set monitor min rx_fcs_rate <rate>

link_protect set monitor min tx_fcs_rate <rate>

link_protect interface concatenate type <olp_id> loop

link_protect interface concatenate type <olp_id> cross

link_protect set heartbeat interval <value>

link_protect set heartbeat timeout <value>

link_protect set abnormal scan_frequency <value>

link_protect slot <slot-id> create <olp_id> <olp_property>

link_protect slot <slot-id> destroy <olp_id>

link_protect slot <slot-id> interface add <olp_id> <smp>

link_protect slot <slot-id> interface delete <olp_id> <smp>

link_protect slot <slot-id> interface type set <olp_id> <if_type>

link_protect slot <slot-id> interface type set <olp_id> <smp> <if_type>

link_protect slot <slot-id> monitor <id> <type> on

link_protect slot <slot-id> monitor <id> <type> off

link_protect slot <slot-id> monitor all <type> on

link_protect slot <slot-id> monitor all <type> off

link_protect slot <slot-id> status show <olp_id>

link_protect slot <slot-id> set inline min rx_rate <rate>

link_protect slot <slot-id> set inline min tx_rx_percent <percent>

link_protect slot <slot-id> set inline min rx_fcs_rate <rate>

link_protect slot <slot-id> set inline min tx_fcs_rate <rate>

link_protect slot <slot-id> set monitor min tx_rate <rate>

link_protect slot <slot-id> set monitor min rx_tx_percent <percent>

link_protect slot <slot-id> set monitor min rx_fcs_rate <rate>

link_protect slot <slot-id> set monitor min tx_fcs_rate <rate>

link_protect slot <slot-id> interface concatenate type <olp_id> loop

link_protect slot <slot-id> interface concatenate type <olp_id> cross

link_protect slot <slot-id> set heartbeat interval <value>

link_protect slot <slot-id> set heartbeat timeout <value>

link_protect slot <slot-id> set abnormal scan_frequency <value>
